# Generated by Django 5.1.6 on 2025-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfreelancer',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
